---
title: "Nwadigwu Assignment 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Installs dependent packages
install.packages("pixmap")
library(pixmap)

setwd("C:/Users/MartinNwadiugwu/Desktop/Assignment 1/Assignment 3")


## face_recognize function needs folder path of training data and test data as inputs
require(readr)

##folder path of training data and test data as inputs

test_folder = ("C:/Users/MartinNwadiugwu/Desktop/Assignment 1/Assignment 3/attDataset_export/test")

train_folder = myTestData = ("C:/Users/MartinNwadiugwu/Desktop/Assignment 1/Assignment 3/attDataset_export (2)/train")

#function to read the file paths
facial_recognition <- function(train_folder, test_folder){
  
  ## Creates a new directory for saving the results
  
  dir.create("Results_facial_recog")
  results_folder <- paste(getwd(), "Results_facial_recog/", sep = "/")
  
  ## Converts image matrices to vectors. generating a matrix of all images
  #read pgm pattern of files in the directory
  files <- list.files(pattern = ".pgm", path = train_folder, full.names = T)
  files_1 <- list.files(pattern = ".pgm", path = train_folder)
  
  #read an image file skipping the first 3 rows
  a <- scan(files[1], skip = 3)
  #create a matrix the size of the file
    c <- matrix(0, length(a), length(files))
  for(i in 1:length(files)){
    a <- scan(files[i], skip = 3)
    c[, i] <- a
  }
  
  colnames(c) <- gsub(".pgm", "", files_1)
  
  ## computing the average of the training image sets
  
  av <- as.matrix(apply(c, 1, mean))
  
  ## computes the average images of training set and saving it to a pgm file
  
  a1 <- read.pnm(files[1])
  a1@grey <- matrix(av[, 1], ncol = a1@size[2], nrow = a1@size[1], byrow = T)
  write.pnm(a1, paste(results_folder, "The_average_face.pgm", sep = ""), type = "pgm", forceplain = T)
  
  
  ## subtracts average face from training images from each column and storing it in a matrix
  
  c1 <- c
  for(j in 1:ncol(c)){
    c[, j] <- c[, j] - av[, 1]
  }
  
  ## computing the eigen decomposition of the covarience matrix and generating the eigen values and vectors
  
  cov_mat <- t(c)%*%c
  eig_values <- eigen(cov_mat)$values
  eig_vectors <- eigen(cov_mat)$vectors
  
  ## Left multiply the eigen vectors of the training image matrix and normalizing the vectors to produce eigenfaces
  
  e_mat <-c
  for(l in 1:ncol(eig_vectors)){
    e_mat[, l] <- (c %*% eig_vectors[, l]) 
    e_mat[, l] <- e_mat[,l]/ norm(as.matrix(e_mat[, l]))}
  
  ## Saving the matrix of top 20 eigen faces as .csv file
  write.csv(e_mat[, 1:20], paste(results_folder,"top_20_eigenfaces.csv", sep = ""), quote = F, row.names = F)
  
  
  ## Reads the test directory
  
  files2 <- list.files(pattern = "pgm", path = test_folder, full.names = T)
  files_2 <- list.files(pattern = "pgm", path = test_folder)
  
  ## for images in the test set, substract the avarage face abd compute its coordinate with respect to the subspace 
  
  results <- matrix(0, length(files2), 2)
  distance <- c()
  for(k in 1:length(files2)){
    atest <- scan(files2[k], skip = 3)
    project_test <- t(e_mat[, 1:20]) %*% (atest - av[, 1])
    for(r in 1:length(files)){
      p <- scan(files[r], skip = 3)
      project_train <- t(e_mat[, 1:20]) %*% (p - av[, 1])
      
      #calculates the euclidean distance among the test images and training images
      distance[r] <- sqrt(sum((project_test-project_train)**2))}
    
    ##Assigning each test image to a training image, choosing the training image with the smallest euclidean distance
    
    idx <- which(distance == min(distance))
    results[k, 1] <- substr(files_2[k], 1, 3)
    results[k, 2] <- substr(files_1[idx], 1, 3)}
  
  colnames(results) <- c("Image_from_Testset", "Predicted_image_of_Trainset")
  idx2 <- which(results[, 1] == results[, 2])
  write.csv(results, paste(results_folder,"Prediction_output.csv", sep = ""), quote = F, row.names = F)
  
  ## Calculating the accuracies of the overall predictions and returns the accuracy score
  
  accuracy <- length(idx2)/nrow(results) * 100
  
  print(noquote("THE RESULTS ARE IN THE CURRENT FOLDER"))
  print(noquote("The overall PREDICTED accuracy is:"))
  print(accuracy)
  print(noquote(""))
  print(noquote("***** Reterned Results ******"))
  return(results)
  
}

#for the top eigenfaces
facial_recognition(train_folder, test_folder)

```

## Selecting random 20 eigenfaces 


```{r random}

facial_recognition2 <- function(train_folder, test_folder){
  
  ## Creates a new directory for saving the results
  
  dir.create("Results_facial_recog2")
  results_folder <- paste(getwd(), "Results_facial_recog2/", sep = "/")
  
  ## Converts image matrices to vectors and generates a matrix of column vectors of all images
  #read pattern of files in the directory
  files <- list.files(pattern = ".pgm", path = train_folder, full.names = T)
  files_1 <- list.files(pattern = ".pgm", path = train_folder)
  
  #read a file skipping the first 3 rows
  a <- scan(files[1], skip = 3)
  #create a matrix the size of the file
    c <- matrix(0, length(a), length(files))
  for(i in 1:length(files)){
    a <- scan(files[i], skip = 3)
    c[, i] <- a
  }
  
  colnames(c) <- gsub(".pgm", "", files_1)
  
  ## Generates an average image for the training image sets
  
  av <- as.matrix(apply(c, 1, mean))
  
  ## Writes an average images of training images to a file
  
  
  a1 <- read.pnm(files[1])
  a1@grey <- matrix(av[, 1], ncol = a1@size[2], nrow = a1@size[1], byrow = T)
  write.pnm(a1, paste(results_folder, "The_average_face.pgm", sep = ""), type = "pgm", forceplain = T)
  
  
  ## subtracts average face from training images to remove redundancies (conserved features)
  
  c1 <- c
  for(j in 1:ncol(c)){
    c[, j] <- c[, j] - av[, 1]
  }
  
  ## Produces a covarience matrix, that further aids in generating the eigen values and eigen vectors
  
  cov_mat <- t(c)%*%c
  eig_values <- eigen(cov_mat)$values
  eig_vectors <- eigen(cov_mat)$vectors
  
  ## Left multiply the eigen vectors of the training image matrix and normalizing the vectors to produce eigenfaces
  
  e_mat <-c
  for(l in 1:ncol(eig_vectors)){
    e_mat[, l] <- (c %*% eig_vectors[, l]) 
    e_mat[, l] <- e_mat[,l]/ norm(as.matrix(e_mat[, l]))}
  
  ## Saves the matrix of top 20 eigen faces as .csv file
  e_matR = matrix(sample(e_mat[], 206080), ncol = 20)
  write.csv((e_matR[,1:20]), paste(results_folder,"random_20_eigen_faces.csv", sep = ""), quote = F, row.names = F)
  
  ## Reads the test directory
  
  files2 <- list.files(pattern = "pgm", path = test_folder, full.names = T)
  files_2 <- list.files(pattern = "pgm", path = test_folder)
  
  ## projects the face space of the training and test images and calculates the euclidean distance among the test images and training images
  
  results <- matrix(0, length(files2), 2)
  distance <- c()
  for(k in 1:length(files2)){
    atest <- scan(files2[k], skip = 3)
    project_test <- t(e_matR) %*% (atest - av[, 1])
    for(r in 1:length(files)){
      p <- scan(files[r], skip = 3)
      project_train <- t(e_matR) %*% (p - av[, 1])
      distance[r] <- sqrt(sum((project_test-project_train)**2))}
    
    ## Identifies closest training image of the test image
    
    idx <- which(distance == min(distance))
    results[k, 1] <- substr(files_2[k], 1, 3)
    results[k, 2] <- substr(files_1[idx], 1, 3)}
  
  colnames(results) <- c("Image_from_Testset", "Predicted_image_of_Trainset")
  idx2 <- which(results[, 1] == results[, 2])
  write.csv(results, paste(results_folder,"Prediction_output.csv", sep = ""), quote = F, row.names = F)
  
  ## Calculates the accuracies of the overall predictions and returns the accuracy score
  
  accuracy <- length(idx2)/nrow(results) * 100
  
  print(noquote("THE RESULTS ARE IN THE CURRENT FOLDER"))
  print(noquote("The overall PREDICTED accuracy is:"))
  print(accuracy)
  print(noquote(""))
  print(noquote(""))
  print(noquote(""))
  print(noquote("***** Reterned Results ******"))
  return(results)
  
}

#for the top eigenfaces
facial_recognition2(train_folder, test_folder)


```

## The end

